### ISSUE TITLE
User data displays multiple time on a single page

### ISSUE THREAD

**Issue by rsadres** [ericsonmichaelj/Heap-Chrome-Extension#1]
certain user identification, like ID, seem to be recorded multiple times on a single page. Not sure what is causing this to fire multiple times.
![screenshot 2018-05-30 14 10 03](https://user-images.githubusercontent.com/10146234/40752088-acbf0206-6433-11e8-9678-2559191ceaa0.png)

**Comment by ericsonmichaelj** [comment]
This was due to the fact that I was originally logging information every time the heap api was fired, regardless If I had logic in place to handle these requests. 

Heap analytics has been updated so that it fires a log every time an event is fired. So it looks like this

<img width="429" alt="screenshot 2018-06-12 00 11 13" src="https://user-images.githubusercontent.com/6697753/41269806-8b7dfe8e-6dd5-11e8-9185-a7c4a7009242.png">

In addition, logic has been added so that User Properties won't show up blank. There's an issue with using console.table in that it won't show on the console unless the logging occurred WHEN the console was open. 

Latest additional should have all these fixed. Hoped this helped!
